// CatalogFile.swift - reading and writing `models.catalog.tsv`.
//
// The inventory itself is Swift (Catalog.swift), not a parsed resource, and
// that is a deliberate departure from the plan's step 3.1. Making the TSV the
// runtime source of truth means shipping a SwiftPM resource bundle beside the
// binary, and `build/speech` is contractually a single file that other repos
// copy on its own - the same assumption that made stage 2's dynamic xcframework
// kill every build until `build.sh` learned to carry it along. Worse,
// `Bundle.module` traps rather than returning nil when its bundle is missing,
// and because it is a lazy `static let` it would trap on first use rather than
// at launch, so a copied binary would abort partway through a session.
//
// So the file is a generated export rather than an input: `speech catalog
// --tsv` writes it, `docs/models.catalog.tsv` is the checked-in copy Speech.app
// reads without running the binary, and `test.sh` regenerates it and fails on a
// difference. That keeps one source of truth and still gives a script a file to
// read. The parser below exists to prove the format is lossless - a round trip
// through it, under every line ending, is what a test asserts - and to leave
// the door open for reading a file this program did not write.
//
// Every column here is a fact about a row: what it is, where its weights come
// from, how big they are, and what the loaded model says it can do. Nothing in
// this file scores or ranks anything.

import Foundation

/// One line of the catalog file: an inventory row joined with the capability
/// facts its engine reports. The two halves stay separate here for the same
/// reason they are separate everywhere else - the row is what this repository
/// records, the capabilities are what the loaded model answers.
public struct CatalogFileRow: Sendable, Equatable {
    public var row: CatalogRow
    /// Primary subtags the engine claims, empty meaning "any language".
    public var languages: [String]
    /// `batch`, `live`, or both.
    public var modes: [String]
    /// `word_ts`, `seg_ts`, `vocab`, `diarize`, `lang_id`, `lang_hint`.
    public var features: [String]
    public var minimumMacOS: String

    public init(
        row: CatalogRow, languages: [String], modes: [String], features: [String],
        minimumMacOS: String
    ) {
        self.row = row
        self.languages = languages
        self.modes = modes
        self.features = features
        self.minimumMacOS = minimumMacOS
    }

    public init(row: CatalogRow, capabilities: EngineCapabilities) {
        self.init(
            row: row,
            languages: capabilities.languages,
            modes: capabilities.modeFlags,
            features: capabilities.featureFlags,
            minimumMacOS: capabilities.minimumMacOS)
    }
}

public enum CatalogFile {
    /// The column order, which is the format. Documented in `docs/catalog.md`.
    public static let columns = [
        "id", "family", "engine", "role", "source", "file", "params_m", "precision",
        "languages", "modes", "caps", "min_macos", "size_bytes", "label",
    ]

    /// The placeholder for a field that has no value: no repository, no GGUF
    /// file, no published parameter count, no size yet. Distinct from an empty
    /// field, which the parser rejects, so that a missing value is always
    /// visible rather than being a run of adjacent tabs nobody notices.
    public static let none = "-"

    /// The stand-in for "every language", which is how an engine that reports
    /// an empty `languages` list is spelled in the file.
    public static let anyLanguage = "*"

    // MARK: - Writing

    /// Renders the catalog file, comment header included.
    ///
    /// Throws rather than escaping or trimming when a field would break the
    /// format. The alternative is a file that parses back into different data
    /// than went in, and since every field here is a string literal in this
    /// repository, the only way one acquires a tab is a mistake worth stopping
    /// for.
    public static func text(
        _ rows: [CatalogFileRow], generator: String,
        environment: [(key: String, value: String)] = []
    ) throws -> String {
        // The generator string lands in a comment. A newline in it would end
        // the comment and start a line the parser would read as data, which is
        // the one way this writer could emit something it did not intend to.
        guard !generator.contains(where: \.isNewline) else {
            throw SpeechError.runtime("catalog generator string contains a newline")
        }
        var out = """
            # models.catalog.tsv - the model inventory. Format: docs/catalog.md.
            #
            # Generated by `\(generator)`; the source of truth is Catalog.swift joined with each engine's own capability record. Do not edit by hand: test.sh regenerates this file and fails on a difference.
            #
            # Tab-separated, '#' comments, no header row, '\(none)' for a field with no value, '\(anyLanguage)' for a row that accepts any language.
            #
            # \(columns.joined(separator: "\t"))

            """
        if !environment.isEmpty {
            // What produced these answers. The capability columns are read out
            // of the models by a particular engine version on a particular OS,
            // and the sizes are one revision of one repository, so a file
            // without this is a set of claims nobody can date.
            var header = "# Produced by:\n"
            for fact in environment {
                guard !fact.value.contains(where: \.isNewline) else {
                    throw SpeechError.runtime(
                        "catalog environment '\(fact.key)' contains a newline")
                }
                header += "#   \(fact.key): \(fact.value)\n"
            }
            out = header + "#\n" + out
        }
        // The caller supplies the final terminator (the verb's sink adds one),
        // so the rows are joined rather than each terminated. With no rows the
        // header's own newline would become that terminator and the file would
        // end in a blank line.
        guard !rows.isEmpty else { return String(out.dropLast()) }
        var seen: Set<String> = []
        for row in rows {
            guard seen.insert(row.row.id).inserted else {
                throw SpeechError.runtime("catalog has two rows with id '\(row.row.id)'")
            }
        }
        out += try rows.map(line).joined(separator: "\n")
        return out
    }

    static func line(_ entry: CatalogFileRow) throws -> String {
        let row = entry.row
        let fields = [
            row.id,
            row.family.rawValue,
            row.engine,
            row.role.rawValue,
            row.source ?? none,
            row.file ?? none,
            row.parametersM.map(String.init) ?? none,
            row.precision,
            try list(entry.languages, or: anyLanguage, column: "languages", row: row.id),
            try list(entry.modes, or: none, column: "modes", row: row.id),
            try list(entry.features, or: none, column: "caps", row: row.id),
            entry.minimumMacOS,
            row.sizeBytes.map(String.init) ?? none,
            row.label,
        ]
        // A column added to `columns` without a matching field here would make
        // `zip` validate only the shorter prefix and emit short lines that fail
        // to parse somewhere else entirely.
        precondition(
            fields.count == columns.count,
            "catalog writer has \(fields.count) fields for \(columns.count) columns")
        for (column, field) in zip(columns, fields) {
            guard !field.isEmpty else {
                throw SpeechError.runtime(
                    "catalog row '\(row.id)': column '\(column)' is empty; use '\(none)'")
            }
            guard !field.contains("\t"), !field.contains(where: \.isNewline) else {
                throw SpeechError.runtime(
                    "catalog row '\(row.id)': column '\(column)' contains a tab or newline")
            }
        }
        // The parser skips a line whose first non-space character is '#', so an
        // id that starts one would vanish from the file with no error at all.
        guard !fields[0].trimmingCharacters(in: .whitespaces).hasPrefix("#") else {
            throw SpeechError.runtime("catalog row '\(row.id)': an id may not start with '#'")
        }
        // The parser runs every id it reads through the path-traversal gate, so
        // an id the writer accepts but the parser rejects would be a file this
        // program could write and not read back.
        guard (try? EngineSpec.parse(
            catalogID: row.id,
            modelsDirectory: URL(fileURLWithPath: NSTemporaryDirectory()))) != nil else {
            throw SpeechError.runtime("catalog row '\(row.id)': the id is not a usable catalog id")
        }
        // A present value spelled the same as a placeholder comes back as the
        // placeholder's meaning - nil, or "any language" - rather than as
        // itself. The check has to be on the value rather than on the rendered
        // field, because once rendered, a nil written as "-" and a literal "-"
        // are the same string. The numeric columns need no check: an Int never
        // renders as a placeholder.
        for (column, value) in [("source", row.source), ("file", row.file)] {
            guard let value, isPlaceholder(value) else { continue }
            throw SpeechError.runtime(
                "catalog row '\(row.id)': column '\(column)' is the literal '\(value)',"
                + " which the format reserves")
        }
        return fields.joined(separator: "\t")
    }

    static func isPlaceholder(_ field: String) -> Bool {
        field == none || field == anyLanguage
    }

    /// Joins a list, refusing elements that would not survive the split.
    static func list(
        _ elements: [String], or empty: String, column: String, row: String
    ) throws -> String {
        guard !elements.isEmpty else { return empty }
        for element in elements {
            guard !element.isEmpty else {
                throw SpeechError.runtime(
                    "catalog row '\(row)': column '\(column)' has an empty element")
            }
            guard !element.contains(",") else {
                throw SpeechError.runtime(
                    "catalog row '\(row)': column '\(column)' element '\(element)'"
                    + " contains the separator")
            }
            guard !isPlaceholder(element) else {
                throw SpeechError.runtime(
                    "catalog row '\(row)': column '\(column)' element '\(element)'"
                    + " is a reserved placeholder")
            }
        }
        return elements.joined(separator: ",")
    }

    // MARK: - Reading

    /// Parses a catalog file back into rows. Strict on structure and lenient on
    /// nothing: a short line, an unknown family or an unparseable number is an
    /// error naming the line, because a catalog that silently drops a row is a
    /// model that silently disappears from the chooser.
    public static func parse(_ text: String) throws -> [CatalogFileRow] {
        var out: [CatalogFileRow] = []
        var seen: Set<String> = []
        for (index, line) in lines(of: text).enumerated() {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.isEmpty || trimmed.hasPrefix("#") { continue }
            let number = index + 1
            let fields = line.components(separatedBy: "\t")
            guard fields.count == columns.count else {
                throw SpeechError.usage(
                    "catalog line \(number): expected \(columns.count) columns, found \(fields.count)")
            }
            let entry = try row(fields: fields, line: number)
            guard seen.insert(entry.row.id).inserted else {
                throw SpeechError.usage(
                    "catalog line \(number): duplicate id '\(entry.row.id)'")
            }
            out.append(entry)
        }
        return out
    }

    /// Splits a file into lines, whatever wrote it.
    ///
    /// Not `split(separator: "\n")`. Swift makes "\r\n" a single `Character`, so
    /// splitting a CRLF file on "\n" matches nothing: the whole file comes back
    /// as one line, that line starts with '#', and the parser returns zero rows
    /// without an error. A checkout with `core.autocrlf`, a Windows editor or a
    /// catalog from somewhere else would all hit it, which is exactly the case
    /// this parser exists for. Normalizing first is the only spelling that is
    /// correct for all three line endings.
    static func lines(of text: String) -> [Substring] {
        var normalized = text
        if normalized.hasPrefix("\u{FEFF}") { normalized.removeFirst() }
        normalized = normalized
            .replacingOccurrences(of: "\r\n", with: "\n")
            .replacingOccurrences(of: "\r", with: "\n")
        return normalized.split(separator: "\n", omittingEmptySubsequences: false)
    }

    static func row(fields: [String], line: Int) throws -> CatalogFileRow {
        func value(_ column: String) throws -> String {
            guard let index = columns.firstIndex(of: column) else {
                throw SpeechError.usage("catalog line \(line): no column '\(column)'")
            }
            let field = fields[index]
            guard !field.isEmpty else {
                throw SpeechError.usage("catalog line \(line): column '\(column)' is empty")
            }
            return field
        }
        func optional(_ column: String) throws -> String? {
            let field = try value(column)
            return field == none ? nil : field
        }
        func list(_ column: String) throws -> [String] {
            guard let field = try optional(column) else { return [] }
            if field == anyLanguage { return [] }
            return field.components(separatedBy: ",").filter { !$0.isEmpty }
        }
        func number(_ column: String) throws -> Int64? {
            guard let field = try optional(column) else { return nil }
            guard let parsed = Int64(field) else {
                throw SpeechError.usage(
                    "catalog line \(line): column '\(column)' is not a number: '\(field)'")
            }
            guard parsed >= 0 else {
                throw SpeechError.usage(
                    "catalog line \(line): column '\(column)' is negative: '\(field)'")
            }
            // "+42" and "007" both parse, and both write back differently than
            // they were read, so a hand-edited file would not survive a round
            // trip through this program.
            guard String(parsed) == field else {
                throw SpeechError.usage(
                    "catalog line \(line): column '\(column)' is not written plainly: '\(field)'")
            }
            return parsed
        }

        let id = try value("id")
        let familyName = try value("family")
        guard let family = CatalogFamily(rawValue: familyName) else {
            throw SpeechError.usage("catalog line \(line): unknown family '\(familyName)'")
        }
        let roleName = try value("role")
        guard let role = CatalogRole(rawValue: roleName) else {
            throw SpeechError.usage("catalog line \(line): unknown role '\(roleName)'")
        }
        // The engine column is redundant with the id's prefix and is written
        // for a script that greps one column. Disagreement means the file was
        // hand-edited, which is exactly the case this check exists for.
        let engine = try value("engine")
        let parameters = try number("params_m")
        let row = CatalogRow(
            id: id,
            family: family,
            role: role,
            source: try optional("source"),
            file: try optional("file"),
            parametersM: parameters.map { Int($0) },
            precision: try value("precision"),
            sizeBytes: try number("size_bytes"),
            label: try value("label"))
        guard row.engine == engine else {
            throw SpeechError.usage(
                "catalog line \(line): id '\(id)' is not an '\(engine)' row")
        }
        // A catalog id becomes a directory name under the model store, and this
        // is the first place in the program where one can arrive from a file
        // rather than from argv. `EngineSpec.parse` is the gate that already
        // refuses a traversal component; running every parsed id through it
        // closes the door before anything downstream opens it.
        _ = try EngineSpec.parse(
            catalogID: id, modelsDirectory: URL(fileURLWithPath: NSTemporaryDirectory()))
        return CatalogFileRow(
            row: row,
            languages: try list("languages"),
            modes: try list("modes"),
            features: try list("caps"),
            minimumMacOS: try value("min_macos"))
    }
}
