#!/usr/bin/env python3
"""live-report.py - publish the live measurements as docs/benchmarks/live.md
and docs/benchmarks/live-measurements.tsv.

Why this is a separate tool from battery-report.py: a live cell is not a
faster or slower version of a batch cell, it is a different measurement.
`speech eval --live` feeds the audio at its own pace, so the figures that
matter are not throughput but when text first appears, how far behind the
speaker the finals run, and whether any words were lost at the end - and the
corpus matters more than anywhere else, because single sentences hide the
sliding-window losses that continuous speech shows (docs/live.md).

It also cannot sweep. One row of twenty minute-long passages takes twenty
minutes of wall clock, so what exists was measured deliberately, cell by cell,
and tools/live-cells.tsv lists exactly which cells are published and which
corpus each belongs to. Anything measured at a setting nobody ships stays out.

Read by Speech.app, which bundles the TSV beside measurements.tsv and suggests
a model for a language from both.
"""

import argparse
import glob
import json
import os
import sys
import textwrap

REPO = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
DEFAULT_CELLS = os.path.join(REPO, "tools", "live-cells.tsv")
DEFAULT_OUT = os.path.join(REPO, "docs", "benchmarks")

# The corpora a live cell can carry, in publication order. Same ids as the
# language battery's, so a row here and a row in measurements.tsv can be lined
# up by (model, corpus). Kept here rather than imported for the reason
# battery-report.py gives: the two tools run separately.
CORPORA = [
    ("librispeech-continuous-test-clean",
     "LibriSpeech test-clean, continuous", "en",
     "Consecutive utterances of one chapter joined into minute-long passages"
     " (tools/make-continuous-corpus.py). This is the corpus a live row has to"
     " be judged on: a row that loses the tail of long speech loses it here"
     " and nowhere else."),
    ("en_us", "FLEURS English (en_US)", "en",
     "One sentence per recording. Short, clean and read aloud, which is what"
     " makes it a weak test of a streaming row."),
    ("pl_pl", "FLEURS Polish (pl_PL)", "pl",
     "One sentence per recording, as above."),
]

# Languages whose orthography puts no space between words: the whitespace
# tokenized WER is not a word error rate there and CER is the comparable
# figure. Same set as the battery's.
UNSPACED = {"zh", "cmn", "yue", "ja", "th", "km", "lo", "my", "bo"}

TSV_COLUMNS = [
    "model", "corpus", "macos", "language", "rows", "pace", "wer_pct", "cer_pct",
    "peak_memory_bytes", "load_seconds", "first_partial_median_s",
    "final_lag_median_s", "final_lag_worst_s", "finish_median_s",
    "trailing_words_lost", "rows_without_partials", "dropped_buffers", "date",
]

BANNER = (
    "<!-- Generated by tools/live-report.py from the cells listed in\n"
    "     tools/live-cells.tsv. Do not edit by hand. -->\n")


def die(message, status=1):
    print("%s: %s" % (os.path.basename(sys.argv[0]), message), file=sys.stderr)
    sys.exit(status)


def warn(message):
    print("%s: %s" % (os.path.basename(sys.argv[0]), message), file=sys.stderr)


def paragraph(text, width=79):
    """Wrap computed prose the way the hand-written constants are wrapped."""
    return "\n\n".join(
        textwrap.fill(block, width=width, break_long_words=False,
                      break_on_hyphens=False)
        for block in text.split("\n\n"))


def table(rows):
    """A markdown table from a header row and body rows, already stringified."""
    lines = ["| " + " | ".join(rows[0]) + " |",
             "| " + " | ".join("---" for _ in rows[0]) + " |"]
    for row in rows[1:]:
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def read_list(path):
    """The (pattern, corpus, note) lines of the cell list."""
    entries = []
    try:
        with open(path, encoding="utf-8") as handle:
            lines = handle.readlines()
    except OSError as error:
        die("cannot read %s: %s" % (path, error))
    for number, line in enumerate(lines, 1):
        text = line.rstrip("\n")
        if not text.strip() or text.lstrip().startswith("#"):
            continue
        fields = text.split("\t")
        if len(fields) < 2 or not fields[0].strip() or not fields[1].strip():
            die("%s line %d: expected a path and a corpus id" % (path, number))
        entries.append((fields[0].strip(), fields[1].strip(),
                        fields[2].strip() if len(fields) > 2 else ""))
    if not entries:
        die("%s lists no cells" % path)
    return entries


def cell_directories(pattern):
    """Every directory one list entry names, expanded."""
    full = os.path.join(REPO, pattern)
    matches = sorted(path for path in glob.glob(full) if os.path.isdir(path))
    return matches


def read_cell(cell_dir, corpus, note):
    """One cell as a record, or None with a warning when it cannot be read.

    A cell that failed or was interrupted has no summary, which is not an
    error here: the run that made it already reported the failure.
    """
    summary_path = os.path.join(cell_dir, "summary.json")
    try:
        with open(summary_path, encoding="utf-8") as handle:
            summary = json.load(handle)
    except (OSError, ValueError):
        return None
    if not isinstance(summary, dict):
        return None
    live = summary.get("live")
    if not isinstance(live, dict):
        warn("%s has no live block; a batch cell cannot be published here"
             % os.path.relpath(cell_dir, REPO))
        return None
    if corpus == "row.tsv":
        try:
            with open(os.path.join(cell_dir, "row.tsv"), encoding="utf-8") as handle:
                fields = handle.readline().rstrip("\n").split("\t")
        except OSError:
            warn("%s has no row.tsv to take a corpus from"
                 % os.path.relpath(cell_dir, REPO))
            return None
        if len(fields) < 2 or not fields[1]:
            warn("%s: row.tsv names no corpus" % os.path.relpath(cell_dir, REPO))
            return None
        corpus = fields[1]
    pace = live.get("pace", 1)
    try:
        if abs(float(pace) - 1.0) > 0.01:
            warn("%s was measured at pace %s, not real time; its latencies are not"
                 " what a speaker would see" % (os.path.relpath(cell_dir, REPO), pace))
    except (TypeError, ValueError):
        warn("%s records no usable pace" % os.path.relpath(cell_dir, REPO))
    model = str(summary.get("model", ""))
    if not model:
        warn("%s: the summary names no model" % os.path.relpath(cell_dir, REPO))
        return None
    return {
        "model": model,
        "corpus": corpus,
        "language": str(summary.get("language", "-")),
        "os": str(summary.get("os", "")),
        "machine": str(summary.get("machine", "")),
        "date": str(summary.get("date", "")),
        "rows": int(summary.get("rows", 0) or 0),
        "note": note,
        "summary": summary,
        "live": live,
        "path": os.path.relpath(cell_dir, REPO),
    }


def read_cells(list_path):
    cells = []
    seen = {}
    for pattern, corpus, note in read_list(list_path):
        directories = cell_directories(pattern)
        if not directories:
            warn("%s matches no directory" % pattern)
            continue
        found = 0
        for cell_dir in directories:
            cell = read_cell(cell_dir, corpus, note)
            if cell is None:
                continue
            key = (cell["model"], cell["corpus"], cell["os"])
            if key in seen:
                # Two cells for one (model, corpus, macOS) means a re-run. The
                # newer one is the answer; say so rather than silently keeping
                # whichever the glob reached first.
                if cell["date"] <= seen[key]["date"]:
                    continue
                warn("%s replaces the older %s for %s on %s"
                     % (cell["path"], seen[key]["path"], cell["model"], cell["corpus"]))
                cells.remove(seen[key])
            seen[key] = cell
            cells.append(cell)
            found += 1
        if not found:
            warn("%s held no publishable live cell" % pattern)
    return cells


def base_language(tag):
    """The base of a language tag: pl-PL and pl both answer pl."""
    return tag.split("-")[0].lower() if tag else ""


def metric_of(corpus, cells=()):
    """WER, or CER where the language writes no spaces between words.

    The cells decide it, not the corpus id: a corpus this tool has never seen
    still has to be scored on the right metric, and its cells carry the
    language tag `speech` resolved. The CORPORA table is the fallback for a
    cell that recorded no tag at all.
    """
    for cell in cells:
        language = base_language(cell.get("language", ""))
        if language:
            return "cer" if language in UNSPACED else "wer"
    for cid, _title, language, _head in CORPORA:
        if cid == corpus:
            return "cer" if language in UNSPACED else "wer"
    return "wer"


def percent(cell, field):
    return float(cell["summary"].get(field, 0) or 0) * 100


def seconds(cell, field):
    value = cell["live"].get(field)
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def render_seconds(value):
    return "-" if value is None else "%.2f s" % value


def corpus_order(corpus):
    ids = [cid for cid, _t, _l, _h in CORPORA]
    return (ids.index(corpus), corpus) if corpus in ids else (len(ids), corpus)


def by_corpus(cells):
    groups = {}
    for cell in cells:
        groups.setdefault(cell["corpus"], []).append(cell)
    return sorted(groups.items(), key=lambda item: corpus_order(item[0]))


def corpus_head(corpus):
    for cid, title, _language, head in CORPORA:
        if cid == corpus:
            return title, head
    return corpus, ""


def render_words(count):
    if not count:
        return "none"
    return "%d word%s" % (count, "" if count == 1 else "s")


def accuracy_table(cells, metric):
    versions = sorted({cell["os"] for cell in cells if cell["os"]})
    header = ["#", "Model", "Recordings", "WER" if metric == "wer" else "CER",
              "First text", "Finals behind", "Worst", "Tail lost", "Peak memory"]
    if len(versions) > 1:
        header.insert(3, "macOS")
    rows = [header]
    ranked = sorted(cells, key=lambda c: (percent(c, metric), c["model"]))
    for place, cell in enumerate(ranked, 1):
        lost = int(cell["live"].get("trailing_words_lost", 0) or 0)
        memory = int(cell["summary"].get("peak_memory_bytes", 0) or 0)
        name = "`%s`" % cell["model"]
        if cell["note"]:
            name += ", %s" % cell["note"]
        row = [
            str(place),
            name,
            str(cell["rows"]),
            "%.2f%%" % percent(cell, metric),
            render_seconds(seconds(cell, "median_first_partial_seconds")),
            render_seconds(seconds(cell, "median_final_lag_seconds")),
            render_seconds(seconds(cell, "worst_final_lag_seconds")),
            render_words(lost),
            "%.2f GB" % (memory / 1e9) if memory else "-",
        ]
        if len(versions) > 1:
            row.insert(3, cell["os"] or "-")
        rows.append(row)
    return table(rows)


def corpus_section(corpus, cells):
    title, head = corpus_head(corpus)
    metric = metric_of(corpus, cells)
    lines = ["### %s" % title, ""]
    if head:
        lines += [paragraph(head), ""]
    lines += [paragraph("%d row%s, ranked by %s."
                        % (len(cells), "" if len(cells) == 1 else "s",
                           metric.upper())), ""]
    lines += [accuracy_table(cells, metric), ""]
    return "\n".join(lines)


HEAD = """# Live measurements

What each live row does when the audio arrives at the pace of speech, measured
with `speech eval --live` on one Mac. Four figures decide whether a row is
usable live, and only the first is accuracy:

- **WER** (CER where the script writes no spaces) - scored on the same
  references as the batch battery, so a row's live and batch figures can be
  compared directly.
- **First text** - the median wait before anything appears. A row with a dash
  never emitted a partial: its text arrives only as finals.
- **Finals behind** - the median, and the worst, delay between a sentence
  ending and its final text.
- **Tail lost** - words missing from the end of a recording. Anything but
  "none" is a defect in the row's own windowing, not a speed problem.

Throughput is deliberately absent: at a pace of 1.0 every row runs at real
time by construction, and a row too slow to keep up shows it as dropped
buffers instead (the last column of the TSV).

**The corpus decides what a live figure means.** A row that drops the tail of
long speech scores well on single sentences and badly on continuous passages,
which is why both are published and why a figure without its corpus is
useless. The Recordings column is the sample a row was measured on, and a row
measured on a handful of them separates nothing.
"""

TAIL = """## What is missing, and why

Two gaps, both from the cost of measuring at real time:

- **Languages.** Only the streaming rows' English is a full battery. Polish
  exists for the two rows a sweep passed through at their shipping setting, and
  no other language has a live cell at all. A language with no row here is not
  a language these rows fail at; it is a language nobody has measured live.
- **Re-runs.** `ggml.nemotron-3.5-asr-streaming-0.6b`'s final lag was measured
  before the commit-freeze workaround this build carries (docs/live.md): its
  accuracy is unaffected and its lag figure is not what the shipping build
  does. The row needs a re-run, and the battery takes hours.

The raw cells, the sweeps at settings nobody ships, and the reasoning behind
each row's chunk length are in docs/live.md and in the repository's `Private/`.
"""


def document(groups, prov):
    parts = [BANNER, HEAD, "", "## Provenance", "",
             paragraph("Machine %s, macOS %s, measured %s to %s, %d cells, from "
                       "tools/live-cells.tsv."
                       % (prov["machine"], prov["os"], prov["first"], prov["last"],
                          prov["cells"])),
             "", "## The rows, by corpus", ""]
    for corpus, cells in groups:
        parts.append(corpus_section(corpus, cells))
    parts.append(TAIL)
    return "\n".join(parts)


def tsv_document(cells, prov):
    lines = ["# Produced by:",
             "#   report: tools/live-report.py",
             "#   machine: %s" % prov["machine"],
             "#   macos: %s" % prov["os"],
             "#   measured: %s to %s" % (prov["first"], prov["last"]),
             "#",
             "# live-measurements.tsv - one row per live cell: a model, a",
             "# corpus and the macOS version it was measured on. Generated by",
             "# tools/live-report.py; do not edit by hand.",
             "#",
             "# pace is the speed the audio was fed at; 1.0 is real time, the",
             "# only pace a live figure means anything at. wer_pct and cer_pct",
             "# are corpus-level percentages. The second figures come from the",
             "# run's live block: first_partial_median_s is empty for a row",
             "# that emits no partials, final_lag_* is how far finals run",
             "# behind the speaker (empty when no final could be timed), and",
             "# trailing_words_lost is words missing from the end of a",
             "# recording - a defect, not a delay.",
             "#",
             "# Coverage is thin on purpose: real-time measurement costs the",
             "# length of the audio. Read a missing (model, language) as not",
             "# measured, never as a failure.",
             "#",
             "\t".join(TSV_COLUMNS)]
    for cell in sorted(cells, key=lambda c: (corpus_order(c["corpus"]), c["model"])):
        summary = cell["summary"]
        live = cell["live"]
        first = seconds(cell, "median_first_partial_seconds")
        lag = seconds(cell, "median_final_lag_seconds")
        worst = seconds(cell, "worst_final_lag_seconds")
        lines.append("\t".join([
            cell["model"], cell["corpus"], cell["os"] or "-", cell["language"],
            str(cell["rows"]),
            "%.2f" % float(live.get("pace", 1) or 1),
            "%.2f" % percent(cell, "wer"),
            "%.2f" % percent(cell, "cer"),
            str(summary.get("peak_memory_bytes", 0)),
            "%.2f" % float(summary.get("load_seconds", 0) or 0),
            "" if first is None else "%.2f" % first,
            "" if lag is None else "%.2f" % lag,
            "" if worst is None else "%.2f" % worst,
            "%.2f" % (seconds(cell, "median_finish_seconds") or 0),
            str(int(live.get("trailing_words_lost", 0) or 0)),
            str(int(live.get("rows_without_partials", 0) or 0)),
            str(int(live.get("dropped_buffers", 0) or 0)),
            cell["date"] or "-",
        ]))
    return "\n".join(lines) + "\n"


def one_value(cells, key):
    values = sorted({cell[key] for cell in cells if cell[key]})
    return " / ".join(values) if values else "unknown"


def provenance(cells):
    dates = sorted(cell["date"] for cell in cells if cell["date"])
    return {
        "machine": one_value(cells, "machine"),
        "os": one_value(cells, "os"),
        "first": dates[0][:10] if dates else "unknown",
        "last": dates[-1][:10] if dates else "unknown",
        "cells": len(cells),
    }


def write(path, text, check):
    """Write a document, or under --check report whether it would change."""
    try:
        with open(path, encoding="utf-8") as handle:
            current = handle.read()
    except OSError:
        current = None
    if current == text:
        return True
    if check:
        print("stale: %s" % os.path.relpath(path, REPO))
        return False
    scratch = "%s.part.%d" % (path, os.getpid())
    try:
        with open(scratch, "w", encoding="utf-8") as handle:
            handle.write(text)
        os.replace(scratch, path)
    except OSError as error:
        try:
            os.remove(scratch)
        except OSError:
            pass
        die("could not write %s: %s" % (path, error))
    print("wrote %s" % os.path.relpath(path, REPO))
    return True


def main():
    parser = argparse.ArgumentParser(
        description="Publish the live cells as docs/benchmarks/live*.")
    parser.add_argument("--cells", default=DEFAULT_CELLS,
                        help="the cell list to read (default %s)"
                             % os.path.relpath(DEFAULT_CELLS, REPO))
    parser.add_argument("--out", default=DEFAULT_OUT,
                        help="where the documents go (default %s)"
                             % os.path.relpath(DEFAULT_OUT, REPO))
    parser.add_argument("--check", action="store_true",
                        help="write nothing; exit 1 if a document is out of date")
    options = parser.parse_args()

    cells = read_cells(options.cells)
    if not cells:
        die("no publishable live cell in %s" % os.path.relpath(options.cells, REPO))
    groups = by_corpus(cells)
    prov = provenance(cells)

    if not options.check:
        try:
            os.makedirs(options.out, exist_ok=True)
        except OSError as error:
            die("cannot create %s: %s" % (options.out, error))

    documents = [("live.md", document(groups, prov)),
                 ("live-measurements.tsv", tsv_document(cells, prov))]
    current = True
    for name, text in documents:
        if not write(os.path.join(options.out, name), text, options.check):
            current = False
    if options.check and not current:
        die("the checked-in live report does not match the cells. "
            "Run tools/live-report.py.", 1)
    if options.check:
        print("docs/benchmarks/live* is current.")


if __name__ == "__main__":
    main()
